### PR TITLE
Option flags

### PR DESCRIPTION
**Pull request by ghost**
Cleanup, adds test

1. Renamed `is_rate_limited` to `sleep_if_needed` to better clarify
    behavior
2. Extract rate limiting error to a module constant
3. Add test suite and required dependencies
        Run 'nosetests' from your virtual environment to see it in action
4. Wrapped long lines

### CODE REVIEW

**Comment by milangfx** [comment]
I would leave the `if (anyTrue and anyFalse)` check so people at least get notified when they try to do  `--user-list --no-s3-scan --link-scan`, and to avoid unexpected behaviour.

**Comment by milangfx** [comment]
https://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse
This is the best thing I found for the parameter handling. Also, there's `parser.add_mutually_exclusive_group(required=False)` which should protect against `command --feature --no-feature`, if we want that.

But this doesn't solve the problem of having to maintain two lists, and no doubt there's a better way of doing that than what I put together quickly.

**Comment by emtunc** [comment]
Hello @influenza ! Thank you for the PR - wondering if it would be a good idea to separate out testing to a separate branch? My knowledge is very limited in this area but it feels odd introducing dependencies (in requirements.txt) that won't be used by most/any of the users of the tool?

Are you able to join the public Slack Workspace I set up? Not an issue if you can't but wanted to discuss some testing integrations I was playing with earlier today.

**Comment by influenza** [comment]
That makes a lot of sense actually. I'll pop into the slack later on.
Thanks!

**Pull request merged**
