### PR TITLE
Add timestamp to file names

### PR DESCRIPTION
**Pull request by milangfx**
Fix for #14

### CODE REVIEW

**Comment by influenza** [comment]
I agree with your thinking @milangfx - it's a timestamp for the whole execution of the run, rather than when each file is created

**Comment by MartinIngesen** [comment]
Wouldn't it be better to add a timestamp to the folder that is created for the workspace?

**Comment by influenza** [comment]
@emtunc for this purpose, it's unlikely that the `with open` you mention would be a big source of execution time. I do agree that accumulating the results and writing them out at the end is a better way to structure the code.

@MartinIngesen I like your idea about time-stamping the folder rather than the files within the folder. That would fix the clobber vs append issue that is being discussed, but also organize the output better. I also agree an output destination flag would be useful. I can work on that this evening.

**Comment by emtunc** [comment]
@milangfx you okay syncing the latest changes? I like the idea of time-stamping the entire folder as opposed to individual files. What do you think?

**Comment by milangfx** [comment]
Agree, timestamp on the folder is a better solution.

**Pull request closed without merging**
